### ISSUE TITLE
Where's the .exe?

### ISSUE THREAD

**Issue by tliffick** [rabanti-github/Media-Extractor#3]
I'm struggling to find the .exe to actually use the tool.  it's been a super long day and just assuming I'm an idiot and can't find it.  Please help!

**Comment by rabanti-github** [comment]
Do you try to build it from source (with Visual Studio / Visual Studio Code), or do you just want to run the application as is?

For the later one:
You find the **latest version** here: [https://github.com/rabanti-github/Media-Extractor/releases/download/v1.4.1/Release.zip](https://github.com/rabanti-github/Media-Extractor/releases/download/v1.4.1/Release.zip). The exe (MediaExtractor.exe) is right in the top directory of the zip file.

If you have compiled the project with Visual Studio, you should find the exe in the folder of your project at: "\MediaExtractor\bin\Debug" or "\MediaExtractor\bin\Release"

Could you manage to find / run it?

Regards

**Comment by rabanti-github** [comment]
So, I assume this is solved. Please reopen, if there are any further problems.
